apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eve
  strategy: {}
  template:
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://{{ .Values.mongo.host }}/db
        image: eve
        imagePullPolicy: ""
        name: eve
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
