apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react
  strategy: {}
  template:
    spec:
      containers:
      - image: react
        imagePullPolicy: ""
        name: react
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
